services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vsa_sql_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=VerticalPassword123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"  
    volumes:
      - vsa_sql_data:/var/opt/mssql  

volumes:
  vsa_sql_data:
    driver: local